### ISSUE TITLE
[Question] Is it possible to minify some part of css file?

### ISSUE THREAD

**Issue by iamfrntdv** [ben-eb/cssnano#355] opened 2017-02-20 15:30 UTC
Stylelint has ability to be disabled for some css rules:
```
/* stylelint-disable */
a {}
/* stylelint-enable */
```
Is it possible to do something like this with cssnano?

**Comment by ben-eb** [comment] 2017-02-20 15:34
Hi @iamfrntdv,

This is a duplicate of https://github.com/ben-eb/cssnano/issues/344. 😄

**Closed by ben-eb** 2017-02-20 15:34 UTC
Labels: duplicate
