### ISSUE TITLE
'TypeError: Cannot call method 'indexOf' of undefined' when uglifying CSS

### ISSUE THREAD

**Issue by lsdafjklsd** [ben-eb/cssnano#52] opened 2015-08-27 19:59 UTC
I'm getting this error on a few of my CSS files when running `webpack -p`, something about uglifying the CSS. Anyone recognize an error like this, or can point me in the direction of a more detailed stack trace? I get the error on 7 out of 100 or so css files. Combed through the files and couldn't find any weird syntax stuff.

```
ERROR in ./~/css-loader!./~/cssnext-loader!./app/styles/index.css
TypeError: Cannot call method 'indexOf' of undefined
```

Any help would be greatly appreciated.

**Comment by ben-eb** [comment] 2015-08-27 20:23
I'm not a webpack user, a full stack trace would be useful. Can you reproduce with cssnano standalone?

**Comment by timkelty** [comment] 2015-09-10 19:24
I'm getting the same error compiling with gulp.

I'm just passing cssnano as plugin to gulp-postcss, I'm _not_ using `gulp-cssnano`
```
[15:20:45] 'build:css' errored after 677 ms
[15:20:45] TypeError in plugin 'gulp-postcss'
Message:
    Cannot read property 'indexOf' of undefined
Details:
    domainEmitter: [object Object]
    domain: [object Object]
    domainThrown: false
```

**Comment by ben-eb** [comment] 2015-09-10 19:35
@timkelty Would it be possible to get a full stack trace please?

**Comment by timkelty** [comment] 2015-09-10 19:36
Seems to break on this bit of CSS (imported from https://github.com/suitcss/components-button)
```
.Button {
  background: transparent;
  border-color: var(--Button-border-color);
  border-style: solid;
  border-width: var(--Button-border-width);
  box-sizing: border-box; /* 2 */
  color: var(--Button-color); /* 3 */
  cursor: pointer;
  display: inline-block;
  font: var(--Button-font); /* 4 */
  line-height: normal; /* 5 */
  margin: 0;
}
```

If I get rid of the line comments (`/* 1 */`), no error.

**Comment by timkelty** [comment] 2015-09-10 19:37
Futher testing: doesn't seem to be relate to `var()` stuff at all, seems to just be choking on those comments.

**Comment by ben-eb** [comment] 2015-09-10 19:38
CLI seems fine to me.

```css
.Button{background:transparent;border:var(--Button-border-width) solid var(--Button-border-color);box-sizing:border-box;color:var(--Button-color);cursor:pointer;display:inline-block;font:var(--Button-font);line-height:normal;margin:0}
```

Would it be possible to share a small test case where the error can be reproduced?

**Comment by timkelty** [comment] 2015-09-10 19:41
Yep -CLI works for me too. Let me put together a test case.

**Comment by timkelty** [comment] 2015-09-10 19:49
Here's my config: https://gist.github.com/timkelty/2cb9249ac9868a1d721c

**Comment by timkelty** [comment] 2015-09-10 19:51
The conflicting plugins seems to be able to boil down to:
```
    require('postcss-map')({
      basePath: path.join(config.paths.srcAssets, 'json'),
      maps: ['breakpoints.json']
    }),
    require('postcss-map')({
      basePath: mapDir,
      maps: mapFiles
    }),
    require('cssnano')({
      'autoprefixer': false
    }),
```

If I get rid of cssnano, or either 1 of the `postcss-map` items, no error.....very weird.

**Comment by ben-eb** [comment] 2015-09-10 19:56
Source files would help. It's a big project so tracking it down to the file/line number that causes the error is pretty crucial. :smile:

**Comment by timkelty** [comment] 2015-09-10 20:04
Sure, I'll post everything that gist.

Also - I just tried to use `gulp-cssnano` instead - no problems.

**Comment by timkelty** [comment] 2015-09-10 20:16
Here's a simplified gulpfile that still produces the error, along with a package.json and css file:
https://gist.github.com/timkelty/2cb9249ac9868a1d721c#file-gulpfile-simplified-js

**Comment by timkelty** [comment] 2015-09-10 20:29
More testing: 
If I separate the `cssnano` call into a separate gulp-postcss call, there is no error:

```
var path        = require('path');
var config      = require(path.join(process.cwd(), 'gulpfile.js/config'));
var gulp        = require('gulp');
var postcss     = require('gulp-postcss');
var browserSync = require('browser-sync').get('serve');
var gulpif      = require('gulp-if');
var srcDir      = path.join(config.paths.srcAssets, 'css/');
var src         = path.join(srcDir, '*.css');
var dest        = path.join(config.paths.destAssets, 'css');
var sourcemaps  = require('gulp-sourcemaps');
var plugins     = [].concat(config.postcss.plugins);
var isDev       = process.env.BUILD_ENV === 'development';

gulp.task('build:css', function() {

  return gulp.src(src)
  .pipe(postcss(plugins))
  .pipe(postcss([
    require('cssnano')({
      'autoprefixer': false
    }),
  ]))
  .pipe(gulp.dest(dest))
  .pipe(browserSync.stream({match: '**/*.css'}));
});
```

**Comment by ben-eb** [comment] 2015-09-10 20:33
Looks like an issue with the AST transforms. I'll try and get your test case running to see if I can get a stack trace.

**Comment by timkelty** [comment] 2015-09-10 20:46
Ok - `gulp build:css --trace` was fairly incomprehensible, not quite sure how to tell what file/line `gulp-postcss` is choking on in its processing.

**Comment by ben-eb** [comment] 2015-09-10 21:25
Note that it's possible to get a stack by doing this:

```js
.pipe(postcss(/* ... */))
  .on('error', function (e) { throw e.stack });
```

I found the problem and it was resolved in https://github.com/ben-eb/postcss-merge-longhand/commit/21bf9421d18a5fc863b92d953063977367ae66e0 (2.0.1). Thanks for providing your source code! :smile:

**Closed by ben-eb** 2015-09-10 21:25 UTC

**Comment by timkelty** [comment] 2015-09-11 12:39
Works great, thanks!
Thanks for letting me on how to get a stack trace, been wondering about that for while.
