### ISSUE TITLE
Whitespace not removed in some case instances

### ISSUE THREAD

**Issue by benfrain** [ben-eb/cssnano#26] opened 2015-06-30 13:04 UTC
Just trying this for the first time. Config is via PostCSS plugin inside a gulp task. No options set and I get weird whitespace included in lots of cases. Here is a tiny snippet:

```
background-repeat:no-repeat}.sport_1:before,.sport_31:before,.sport_74:before,.sport_82:before{
	background-position:50% 2px}.sport_2:before,.sport_73:before,.sport_81:before{
	background-position:50% -1081px}.sport_3:before{
	background-position:50% -2109px}.sport_4:before,.sport_85:before{
	background-position:50% -3135px}.sport_5:before,.sport_129:before,.sport_130:before,.sport_131:before,.sport_132:before,.sport_133:before,.sport_134:before,.sport_135:before,.sport_136:before,.sport_137:before,.sport_800:before,.sport_996:before{
	background-position:50% -57px}.sport_6:before{
	background-position:50% -855pt}.sport_7:before{
	background-position:50% -2166px}.sport_8:before{
	background-position:50% -2337px}.sport_9:before{
```

Expected:

```
background-repeat:no-repeat}.sport_1:before,.sport_31:before,.sport_74:before,.sport_82:before{background-position:50% 2px}.sport_2:before,.sport_73:before,.sport_81:before{background-position:50% -1081px}.sport_3:before{background-position:50% -2109px}.sport_4:before,.sport_85:before{background-position:50% -3135px}.sport_5:before,.sport_129:before,.sport_130:before,.sport_131:before,.sport_132:before,.sport_133:before,.sport_134:before,.sport_135:before,.sport_136:before,.sport_137:before,.sport_800:before,.sport_996:before{background-position:50% -57px}.sport_6:before{background-position:50% -855pt}.sport_7:before{background-position:50% -2166px}.sport_8:before{background-position:50% -2337px}.sport_9:before{
```

**Comment by ben-eb** [comment] 2015-06-30 13:08
Strange. Do you have something that I could reproduce this with?

**Comment by benfrain** [comment] 2015-06-30 13:34
Bit diffiicult to create a reduction as I'm knee-deep in a shed load of CSS but this in the CSS:

```
.ipe-LiveAlertsControlContainer {
	display: none;
	align-items: center;
	min-height: $size-quadruple;
}
```

Is going through simpleVars and autoprefixer and nano and coming out like this:

```
.ipe-LiveAlertsControlContainer{
	min-height:44px;
	-webkit-box-align:center;
	-webkit-align-items:center;
	-ms-flex-align:center;
	align-items:center}
```

**Comment by ben-eb** [comment] 2015-06-30 13:40
OK. You might like to try using cssnano using the gulp plugin in the meantime, as this may be an AST issue.

**Comment by benfrain** [comment] 2015-06-30 14:14
Just tried the gulp-cssnano and have a different issue! Sorry! opened a ticket over there: https://github.com/ben-eb/gulp-cssnano/issues/2

**Comment by faergeek** [comment] 2015-07-15 17:55
For me this happens mostly in media queries. Going to try to create reduced test case for that ASAP.

**Comment by faergeek** [comment] 2015-07-31 15:43
@benfrain Do you have `@media print` in your stylesheet?

**Comment by benfrain** [comment] 2015-07-31 15:45
No, I don't. :)

**Comment by faergeek** [comment] 2015-07-31 15:47
It's weird, I can reproduce it just by adding/removing `box-shadow` inside `@media print`, value doesn't matter.

**Comment by faergeek** [comment] 2015-08-01 05:40
@benfrain Do you have a similar issue with `@media print` and `box-shadow`?

**Comment by faergeek** [comment] 2015-08-01 10:48
To fix it we can reset styleCache(`css.styleCache = {};` or `css.styleCache = undefined;`) here https://github.com/ben-eb/cssnano/blob/master/lib/core.js#L42 or try to fix plugins which loose styles (e.g. indentation) while processing (because of cloning and such things), in my case it's [css-mqpacker](https://github.com/hail2u/node-css-mqpacker).

/cc @hail2u

**Comment by ben-eb** [comment] 2015-08-01 12:11
@faergeek Is it possible to provide some fixture where this is failing?

**Comment by faergeek** [comment] 2015-08-01 12:45
Here it is https://github.com/faergeek/cssnano-testcase

What happens:

1. `css-mqpacker` loses formatting styles when clonning at-rules (https://github.com/hail2u/node-css-mqpacker/blob/master/lib/css-mqpacker.js#L177).
1. inside `cssnano` `autoprefixer-core` removes unneeded properties, causing it to get formatting styles from defaults (https://github.com/postcss/autoprefixer-core/blob/master/lib/processor.coffee#L80 and https://github.com/postcss/postcss/blob/master/lib/node.js#L3-L15) and saves it as `styleCache` at root node.
1. `cssnano-core` (https://github.com/ben-eb/cssnano/blob/master/lib/core.js) removes whitespaces, but `css.styleCache` is applied anyway.

**Comment by ben-eb** [comment] 2015-08-01 16:46
@faergeek Thanks. :+1: Looks like its a problem with autoprefixer, as disabling it yields this output, which is larger obviously but spaces are correct:

```css
.test{width:500px}@media print{.test{-webkit-border-radius:0;border-radius:0;-webkit-box-shadow:none;box-shadow:none}}
```

/cc @ai

**Comment by faergeek** [comment] 2015-08-01 16:57
It isn't problem with autoprefixer. I'd rather say it's problem with PostCSS, but it isn't either.
The problem is that `style` function tries to find formatting styles, doesn't find them and falls back to defaults, and defaults have 4-space indentation and such things. Autoprefixer just queries that info.

You can disable autoprefixer-core or mq-packer or remove prefixed props, but it isn't sign that something of this is working wrong.

They just work wrong together : -)

So I'd prefer clearing styleCache or fix css-mqpacker or better both of these.

**Comment by ben-eb** [comment] 2015-08-01 17:00
OK, makes sense.

@benfrain What other plugins were you using?

**Comment by faergeek** [comment] 2015-08-01 17:04
Also will be helpful if you say what preprocessor and may be framework you're using.
For example, I got prefixed props in my stylesheets from kouto-swiss (stylus framework), so when I commented it out, the problem disappeared, it produced a lot of WTFs :-)

**Comment by benfrain** [comment] 2015-08-01 17:06
Will check Monday when back in the office :)

**Comment by ai** [comment] 2015-08-01 19:43
@faergeek thank for invastigate into Code Style system so deep.

I agree that we should change it in 5.0, but I didn’t hae ideas right now. Maybe you hae ideas? You are welcome for any brainstorm suggestion: https://github.com/postcss/postcss/issues/199

**Comment by faergeek** [comment] 2015-08-04 07:16
@benfrain Do you have a similar issue? Can you tell about your setup?

**Comment by meuwka** [comment] 2015-08-06 23:03
@faergeek I have same issue

as a quick fix I just change order from 1) autoprefixer-core 2) cssnano 
to 1) cssnano 2) autoprefixer-core

strange but it works
but hope it will be fixed in the future

**Comment by faergeek** [comment] 2015-08-07 05:31
Yeah, it seems strange, but there's just autoprefixer-core used inside cssnano (for removing unneeded prefixes).

So you can just configure it in both places (provide the list of supported browsers) or even just disable it in cssnano config instead of changing order and it should still work.

**Comment by meuwka** [comment] 2015-08-07 08:38
I try to set autoprefixer option in cssnano to false - not working

Is it possible to configure list of supported browsers  in cssnano, really?

**Comment by ben-eb** [comment] 2015-08-07 08:45
@meuwka Yep:

```js
{
  autoprefixer: {
    browsers: 'last 2 versions'
  }
}
```

**Comment by faergeek** [comment] 2015-08-07 08:45
Docs say that it accepts autoprefixer configuration directly http://cssnano.co/options/ or just `false`.
What other plugins do you use before autoprefixer and cssnano? Some preprocessors/frameworks?

**Comment by benfrain** [comment] 2015-08-07 09:05
@ben-eb as far as I can tell, here were the plugins I was using. 

```
var postcss = require("gulp-postcss");
    var postcssImport = require("postcss-import");
    var nano = require("gulp-cssnano");
    var autoprefixer = require("autoprefixer");
    var map = require("postcss-map");
    var simpleVars = require("postcss-simple-vars");
    var cssfor = require("postcss-for");
    var mixins = require("postcss-mixins");
    var colorFunction = require("postcss-color-function");
    var nested = require("postcss-nested"); 
    var calc = require("postcss-calc");
    var sourcemaps = require("gulp-sourcemaps");
    var concat = require("gulp-concat");
```

**Comment by meuwka** [comment] 2015-08-07 09:40
@ben-eb thanks!
@faergeek postcss-import, postcss-simple-vars, postcss-nested, css-mqpacker, autoprefixer-core, cssnano

didnt help:
- disable 'css-mqpacker' (only 'autoprefixer-core')
- sync list of supported browsers
```
require('autoprefixer-core')({browsers: ['last 2 versions']}),
require('cssnano')({autoprefixer: {browsers: 'last 2 versions'}})
```
Result:
![screen shot on 2015-08-07 at 12-37-01](https://cloud.githubusercontent.com/assets/2752193/9133063/24729644-3d01-11e5-954f-d26d03ce125a.png)

**Comment by ben-eb** [comment] 2015-08-07 09:45
Note that you can work around this problem by running cssnano separately, after your other PostCSS plugins. e.g (gulp):

```js
var gulp = require('gulp');
var postcss = require('gulp-postcss');
var nano = require('gulp-cssnano');

gulp.task('css', function () {
  return gulp.src('*.css')
    .pipe(postcss([ /* plugins */ ]))
    .pipe(nano())
    .pipe(gulp.dest('build'));
});
```

**Comment by faergeek** [comment] 2015-08-07 09:47
I think it's even possible with just `cssnano`, just second postcss pipe

**Comment by ben-eb** [comment] 2015-08-07 09:48
Indeed, you could do that too. :+1:

**Comment by meuwka** [comment] 2015-08-07 10:01
@benfrain @faergeek this idea has not entered my head before, thanks!

```
.pipe(postcss([/* plugins */]))
.pipe(postcss([require('cssnano')]))
```

**Comment by faergeek** [comment] 2015-08-07 10:16
@ben-eb So what about clearing styleCache?

**Comment by ben-eb** [comment] 2015-08-07 10:36
@faergeek Alright, I tried that out in your example repo and it seems to work! So I just need to come up with some test case so people can try it out.

**Comment by faergeek** [comment] 2015-08-07 11:40
@ben-eb I think as a test case you can just clone something around and expect good minification as output.

**Comment by ben-eb** [comment] 2015-08-07 14:12
Feedback on https://github.com/ben-eb/cssnano/pull/42 is appreciated. This feels like a *not ideal* way of doing this. :smile:

**Closed** 2015-08-12 09:27 UTC
