### ISSUE TITLE
border: 0 is removed from output CSS

### ISSUE THREAD

**Issue by davidtheclark** [ben-eb/cssnano#104] opened 2016-01-18 19:06 UTC
`border: 0;` is being removed from my output CSS. 

If I switch to `border: none`, I can accomplish the same thing and cssnano leaves the `border` declaration alone --- but I believe the removal of `border: 0` is a bug, right?

**Comment by davidtheclark** [comment] 2016-01-18 19:07
I am using v3.4.0.

**Comment by ben-eb** [comment] 2016-01-18 20:03
Sounds like it; do you have some example that I could reproduce?

**Comment by davidtheclark** [comment] 2016-01-18 20:40
I was running into this in a large codebase, and was able to reproduce the problem just by changing the value on and off and checking the output. I will try to figure out a more reduced test case this evening or soon after.

**Comment by ben-eb** [comment] 2016-01-18 20:46
Can you reproduce with `{mergeRules: false}`?

**Comment by davidtheclark** [comment] 2016-01-18 21:04
Will give it a try.

**Comment by davidtheclark** [comment] 2016-01-18 22:50
Yep, your guess is right on: disabling mergeRules avoids the problem. I will try to get a test for that repo.

**Comment by davidtheclark** [comment] 2016-01-18 22:52
Here is the rule with its adjacent rule:

```css
button {
  background: transparent;
  border: none;
  color: inherit;
  font: inherit;
  margin: 0;
  padding: 0;
  width: auto;
  text-align: left;
  appearance: none;
  user-select: none;
}

button::-moz-focus-inner {
  padding: 0;
  border: 0;
}
```

**Comment by ben-eb** [comment] 2016-01-18 23:05
Yep, I need to do some rewriting of that module. :smile:

**Comment by ben-eb** [comment] 2016-04-17 12:14
I couldn't reproduce an error with that test case, but this should now be resolved by https://github.com/ben-eb/postcss-merge-rules/commit/112fd62b85cd413ad72e57d4a6c2cdf16d564744. Can you please confirm?

**Comment by ben-eb** [comment] 2016-05-10 21:00
I'm going to mark this as resolved as the thread is now stale. Please feel free to reopen with a reproducible test case if this is still an issue.

**Closed by ben-eb** 2016-05-10 21:00 UTC
Labels: bug
