### ISSUE TITLE
Cannot read property 'pre' of undefined

### ISSUE THREAD

**Issue by kud** [ben-eb/cssnano#16] opened 2015-05-26 14:50 UTC
```
events.js:141
      throw er; // Unhandled 'error' event
            ^
TypeError: Cannot read property 'pre' of undefined
    at /Users/kud/Projects/_playmedia/play-tv/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/cssnano/lib/functionOptimiser.js:29:22
    at eachCssFunction (/Users/kud/Projects/_playmedia/play-tv/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/cssnano/lib/util/eachCssFunction.js:12:59)
    at /Users/kud/Projects/_playmedia/play-tv/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/cssnano/lib/functionOptimiser.js:26:9
    at /Users/kud/Projects/_playmedia/play-tv/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss/lib/container.js:126:34
    at /Users/kud/Projects/_playmedia/play-tv/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss/lib/container.js:104:26
    at Rule.each (/Users/kud/Projects/_playmedia/play-tv/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss/lib/container.js:91:22)
    at Rule.eachInside (/Users/kud/Projects/_playmedia/play-tv/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss/lib/container.js:103:21)
    at /Users/kud/Projects/_playmedia/play-tv/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss/lib/container.js:107:32
    at Root.each (/Users/kud/Projects/_playmedia/play-tv/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss/lib/container.js:91:22)
    at Root.eachInside (/Users/kud/Projects/_playmedia/play-tv/node_modules/gulp-cssnext/node_modules/cssnext/node_modules/postcss/lib/container.js:103:21)
```

**Comment by ben-eb** [comment] 2015-05-26 14:52
What is the minimum CSS needed to reproduce this error?

**Comment by kud** [comment] 2015-05-26 14:58
```css
/*----------Button----------*/
.Button {
  display: inline-block;
  margin-bottom: .5em;
  padding: .5em 2em;
  text-decoration: none !important;
  font-weight: 700;
  border-radius: 20px;
  color: #000;
  text-align: center;
  vertical-align: middle;
  cursor: pointer;
  white-space: nowrap;
  font-size: inherit;
  line-height: normal;

}
button {
  background-color: transparent;
  background-image: none;
  user-select: none;
  -webkit-appearance: none;
}
/**
* Remove excess padding and border in Firefox 4+
*/
button::-moz-focus-inner {
  border: 0;
  padding: 0;
}
/*outline chrome */
button:focus {outline:none;}

.Button:hover:not(.is-disabled),
.Button:focus:not(.is-disabled),
.Button:active:not(.is-disabled) {
  text-decoration: none;
}
.Button:hover:not(.is-disabled) {
  color:#fff;
}
.Button--default {
  border: solid 4px var(--wc-background-dark);
}
.Button--default:hover:not(.is-disabled) {
  background-color: var(--wc-background-dark);
}
.Button--action {
  border: solid 4px var(--wc-variant-background-light);
}
.Button--action:hover:not(.is-disabled) {
  background-color: var(--wc-variant-background-light);
}
.Button:disabled,
.Button.is-disabled {
  cursor: default;
  opacity: var(--Button-disabled-opacity);
}
```

via @magsout

**Comment by ben-eb** [comment] 2015-05-26 15:04
Alright. I believe it is the existence of `var` *twice* in `var(--wc-variant-background-light);` which might be throwing off the logic there. Thanks for the report :+1:

**Comment by kud** [comment] 2015-05-26 15:06
You're welcome.

**Comment by magsout** [comment] 2015-05-26 15:06
hum, not sur, I try with:

```
/*----------Button----------*/
.Button {
  display: inline-block;
  margin-bottom: .5em;
  padding: .5em 2em;
  text-decoration: none !important;
  font-weight: 700;
  border-radius: 20px;
  color: #000;
  text-align: center;
  vertical-align: middle;
  cursor: pointer;
  white-space: nowrap;
  font-size: inherit;
  line-height: normal;

}
button {
  background-color: transparent;
  background-image: none;
  user-select: none;
  -webkit-appearance: none;
}
/**
* Remove excess padding and border in Firefox 4+
*/
button::-moz-focus-inner {
  border: 0;
  padding: 0;
}
/*outline chrome */
button:focus {outline:none;}

.Button:hover:not(.is-disabled),
.Button:focus:not(.is-disabled),
.Button:active:not(.is-disabled) {
  text-decoration: none;
}
.Button:hover:not(.is-disabled) {
  color:#fff;
}
.Button--default {
  border: solid 4px var(--wc-background-dark);
}
.Button--default:hover:not(.is-disabled) {
}
.Button--action {
  border: solid 4px var(--wc-variant-background-light);
}
.Button--action:hover:not(.is-disabled) {
}
.Button:disabled,
.Button.is-disabled {
  cursor: default;
  opacity: var(--Button-disabled-opacity);
}

```


Same error, and I removed `var(--wc-variant-background-light);` and `background-color: var(--wc-background-dark);`

**Comment by ben-eb** [comment] 2015-05-26 15:08
I can reproduce with this CSS:

```css
.Button--action:hover:not(.is-disabled) {
    background-color: var(--wc-variant-background-light);
}
```

I'll try and get this fixed first and then see if your whole input is still failing.

**Comment by magsout** [comment] 2015-05-26 15:10
:+1:

**Comment by ben-eb** [comment] 2015-05-26 15:40
Released as `1.2.1`. :smile:

**Comment by kud** [comment] 2015-05-26 16:04
It seems it works for me, thank you very much. ;)

**Comment by ben-eb** [comment] 2015-05-26 16:09
You're welcome!

**Comment by kud** [comment] 2015-05-26 16:18
Well. When I said it works, I talked about the compilation. Because the result doesn't work correctly. Some css lines are lost. :(

**Comment by ben-eb** [comment] 2015-05-26 16:27
@kud I don't see anything missing with your input CSS?

**Comment by kud** [comment] 2015-05-26 16:28
It wasn't mine but the one from @magsout. I'm debugging now my own css to see the difference between minified and not minified.

**Comment by ben-eb** [comment] 2015-05-26 16:33
The only differences that I can see is that the empty rules have been removed, and selectors sorted. This is normal behaviour. :smile:

**Comment by kud** [comment] 2015-05-26 16:34
^^

**Comment by radium-v** [comment] 2015-06-02 20:21
Howdy,

Sorry for replying on a closed ticket, but I'm still experiencing this issue in 1.3.0

We use inline, URL-encoded SVG for gradients in IE9.

```css
.box {
  background-image: url('data:image/svg+xml,%3C%3Fxml%20version%3D%221.0%22%20%3F%3E%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20version%3D%221.1%22%20width%3D%22100%25%22%20height%3D%22100%25%22%20viewBox%3D%220%200%201%201%22%20preserveAspectRatio%3D%22none%22%3E%3ClinearGradient%20id%3D%22gradient%22%20gradientUnits%3D%22userSpaceOnUse%22%20x1%3D%220%25%22%20y1%3D%220%25%22%20x2%3D%22100%25%22%20y2%3D%220%25%22%3E%3Cstop%20offset%3D%220%25%22%20stop-color%3D%22%23414042%22%2F%3E%3Cstop%20offset%3D%22100%25%22%20stop-color%3D%22%23ffffff%22%20stop-opacity%3D%220%22%2F%3E%3C%2FlinearGradient%3E%3Crect%20x%3D%220%22%20y%3D%220%22%20width%3D%221%22%20height%3D%221%22%20fill%3D%22url(%23gradient)%22%20%2F%3E%3C%2Fsvg%3E');
}
```

That line is long, so here's the relevant part:
```
fill%3D%22url(%23gradient)%22
```

Since `encodeURIComponent` doesn't encode parentheses, we get this error when lines like this are encountered. If I manually encode the parentheses then the error goes away, but I'd rather not do that.

**Comment by ben-eb** [comment] 2015-06-02 20:33
@radium-v No problem. Are you getting the same error?

**Comment by ben-eb** [comment] 2015-06-02 20:51
@radium-v Nevermind I think I know the cause. I am thinking that the url() is being 'parsed' twice, which it shouldn't do but the logic for this case is meant to collapse spaces between functions. It doesn't know about the difference between a function inside a string or otherwise. So the parsing could definitely be improved here. I'll reopen this but it will be of a lower priority until https://github.com/ben-eb/postcss-minify-selectors/issues/2 is fixed.

**Closed** 2015-06-14 23:15 UTC
Labels: bug
