### ISSUE TITLE
BrowserslistError: Unknown version 55 of and_chr

### ISSUE THREAD

**Issue by kristoferjoseph** [ben-eb/cssnano#340] opened 2017-01-11 23:10 UTC
If I add `cssnano` to my project I get this error.
If I remove it the error goes away.
Please advise.
Thank you kindly.

**Comment by ben-eb** [comment] 2017-01-11 23:12
Are all of your dependencies up to date? This might be caused by overlapping caniuse-db versions.

**Comment by kristoferjoseph** [comment] 2017-01-11 23:30
Yes. Even after updating all dependencies it still throws this error. I am sad. 😢

**Comment by ben-eb** [comment] 2017-01-11 23:50
That's odd. @sylvainpolletvillard had this issue earlier and it was resolved by updating caniuse-db manually to the latest version. Does this work for you?

**Comment by kristoferjoseph** [comment] 2017-01-12 00:17
How does one go about doing this?
`npm i caniuse-db` ?

**Comment by ben-eb** [comment] 2017-01-12 00:19
Yeah, the current version is `1.0.30000605`; https://github.com/Fyrd/caniuse/commit/67737db4bb193b919d5b3ca8b5d439acf181a7fa

**Comment by sylvainpolletvillard** [comment] 2017-01-12 00:44
Yes, I got the same issue toda and solved it with `npm upgrade caniuse-db`
It works with caniuse-db version 1.0.30000605

**Comment by Thibautj88** [comment] 2017-01-12 16:39
Same error here.
I found that it comes from https://github.com/ben-eb/postcss-merge-rules, that uses caniuse-api@1.5.2.

For now, I only exclude merge-rules from my optimization process:
`cssnano({
          mergeRules: false
        })`

**Comment by poxrud** [comment] 2017-01-13 19:47
Same error, ```npm i caniuse-db --save```  fixed it

**Comment by Dictory** [comment] 2017-01-16 13:23
@kristoferjoseph hm, thanks, that work for me

**Comment by ScottSmith95** [comment] 2017-01-20 22:55
I'm still getting this error, even with the autoprefixer optimisation disabled and after running `npm update caniuse-db`. I've purged my node_modules directory as well.

**Comment by ben-eb** [comment] 2017-01-21 15:33
@ScottSmith95 Does the latest release of browserslist resolve this issue for you? https://github.com/ai/browserslist/issues/110#issuecomment-274257914

**Comment by ScottSmith95** [comment] 2017-01-24 21:56
Yes, looks like this issue is resolved for me now.

**Comment by manuelbieh** [comment] 2017-01-24 21:59
Same error here. Had to pin cssnano@3.9.1. Everything after 3.9.1 throws the error mentioned above.

**Comment by ben-eb** [comment] 2017-01-24 22:06
@manuelbieh Does upgrading browserslist to 1.6 work for you?

**Comment by manuelbieh** [comment] 2017-01-24 22:24
Seems like it is/was something completely different. I had 2 different versions of browserlist installed. One (1.4.0) came with an old version of browserlist and css-loader had its own (1.6.0) and whatever it was, it was broken. I cant say for sure if my downgrade to 3.9.1. really was what fixed it but after getting rid of browserlist 1.4.0 everything works for me now, sorry :smiley:

**Comment by ben-eb** [comment] 2017-01-24 22:25
Alright, cool. Seems like this can be marked resolved now. 😄

**Closed by ben-eb** 2017-01-24 22:25 UTC
Labels: documentation

**Comment by stevenvachon** [comment] 2017-01-30 22:45
I get this error repeatedly on Semaphore CI, but not locally. Dunno which postcss plugin is causing it.

**Comment by GautierT** [comment] 2017-02-09 09:31
Maybe a 
```
npm install -g npm@latest

cd your_project_directory
rm -rf node_modules
npm install
```
can help
https://github.com/facebookincubator/create-react-app/issues/1454#issuecomment-275475646

**Comment by stevenvachon** [comment] 2017-02-09 14:19
It's all a fresh install on CI. Somehow, using `yarn` instead of `npm install` made it work.

**Comment by notacouch** [comment] 2017-03-02 01:16
Started getting this error all of the sudden with a fresh install, setting `mergeRules` to `false` as per @Thibautj88 's comment did the trick for me.

**Comment by ben-eb** [comment] 2017-03-02 02:33
@notacouch Please provide a minimal reproduction, I am not getting this error after the latest browserslist release.

**Comment by notacouch** [comment] 2017-03-02 18:03
@ben-eb Thanks for asking. I had no idea how to go about this or if I could even reproduce it but... I did.

Set up a repo here to demonstrate it:
https://github.com/notacouch/mergerules-bug-test

quoting the commit message:

> Reduced conflicting CSS down to  :target pseudo class and a relative matching selector (the matching selector could be a descendant after :target).
>
> Reduced browserslist issue down to custom stats file with an ‘and_chr’ browser.
>
> Run:
> `gulp 'Copy nested .css files directly to /css/'`

**Comment by ben-eb** [comment] 2017-03-02 21:48
@notacouch Thanks, I've created an issue in Browserslist for this. https://github.com/ai/browserslist/issues/128

**Comment by notacouch** [comment] 2017-03-03 16:06
@ben-eb Thanks for following through with that. They patched that up real quick, too. Nice.

**Comment by sgarcia-dev** [comment] 2017-03-24 22:21
Thank you @GautierT, your solution worked for me.

**Comment by stevenvachon** [comment] 2017-03-24 22:30
@sgarcia-dev this issue should be fixed with the latest versions.
