### ISSUE TITLE
cssnano doesn't strip duplicate padding

### ISSUE THREAD

**Issue by yivo** [ben-eb/cssnano#350] opened 2017-02-01 10:04 UTC
**Input:**
```css
.btn {
    padding: 0;
    padding: 3px 6px;
}
```

**Output:**
```css
.btn{padding:0;padding:3px 6px}
```

**Expected output:**
```css
.btn{padding:3px 6px}
```

**cssnano version:**
```
cssnano v3.10.0 (cli v1.0.5)
```

**Comment by yivo** [comment] 2017-02-01 10:06
Same issue exists for `border` and `border-radius`.

**Comment by ben-eb** [comment] 2017-02-01 10:09
This is a duplicate of https://github.com/ben-eb/cssnano/issues/86.

**Closed by ben-eb** 2017-02-01 10:09 UTC
