### ISSUE TITLE
Minifying background:none shorthand

### ISSUE THREAD

**Issue by yisibl** [ben-eb/cssnano#29] opened 2015-07-09 02:06 UTC
See also: 
https://github.com/jakubpawlowicz/clean-css/issues/150#issuecomment-25641353

**Comment by ben-eb** [comment] 2015-07-09 07:57
Duplicate of https://github.com/ben-eb/cssnano/issues/23. That thread covers why it is not always safe to reduce this.

**Closed by ben-eb** 2015-07-09 07:57 UTC
Labels: duplicate
