### ISSUE TITLE
cssnano not playing nice with font-display

### ISSUE THREAD

**Issue by WDD-Marv** [ben-eb/cssnano#420] opened 2017-10-31 16:01 UTC
In my postcss config I've got font-magician configured to add `font-display: optional;`, but there seems to be an issue with cssnano 3.x/4.x;

after getting errors & hoping that `cssnano@next` would clear it up, I've manually added all the plugins & selectively disabled them until no errors occurred:

```js
[
  require('postcss-colormin')(),
  /*
  require('postcss-convert-values')(),
  */
  require('postcss-discard-comments')(),
  require('postcss-discard-duplicates')(),
  require('postcss-discard-empty')(),
  require('postcss-discard-overridden')(),
  /*
  require('postcss-discard-unused')(),
  */
  require('postcss-merge-idents')(),
  require('postcss-merge-longhand')(),
  require('postcss-merge-rules')(),
  require('postcss-minify-font-values')(),
  require('postcss-minify-gradients')(),
  require('postcss-minify-params')(),
  require('postcss-minify-selectors')(),
  require('postcss-normalize-charset')(),
  require('postcss-normalize-display-values')(),
  require('postcss-normalize-positions')(),
  require('postcss-normalize-repeat-style')(),
  /*
  require('postcss-normalize-string')(),
  */
  require('postcss-normalize-timing-functions')(),
  require('postcss-normalize-unicode')(),
  /*
  require('postcss-normalize-url')(),
  require('postcss-normalize-whitespace')(),
  */
  require('postcss-ordered-values')(),
  require('postcss-reduce-idents')(),
  require('postcss-reduce-initial')(),
  require('postcss-reduce-transforms')(),
  require('postcss-svgo')(),
  require('postcss-unique-selectors')(),
  require('postcss-zindex')(),
]
```

the errors that occur are either `TypeError: value.charCodeAt is not a function` or `TypeError: node.value.replace is not a function` and only occur if the `@font-family` blocks have a `font-display` declaration present, i.e. `font-display: optional ;`

**Comment by evilebottnawi** [comment] 2018-04-19 18:40
@andyjansson very strange, we don't have `font-display` nowhere
@WDD-Marv friendly ping, problem still exists, can you provide more infromation?

**Comment by WDD-Marv** [comment] 2018-05-03 08:33
@evilebottnawi basic reproduction repo posted; issue occurs if either `cssnano` or `cssnano@next` is used, issue does not occur with just `postcss-font-magician`.

**Comment by kuflash** [comment] 2018-06-02 12:36
I'm tried debugging this problem and found strange thing. Perhaps the problem is still in the `postcss-font-magician`, because if we put simple css with `@font-face` rule with font-display property into cssnano, it will work correctly and compress everything. But if we put `postcss-font-magician` into our pipeline of plugins, we catch exception.

Perhaps this is due to [this conversion](https://github.com/jonathantneal/postcss-font-magician/blob/master/index.js#L42) of options transmitted to postcss-font-magician`. Because into end we get decl.value = ['options'], but on idea should receive simply decl.value = 'options'.

Maybe I'm wrong, then correct me.

**Comment by WDD-Marv** [comment] 2018-06-04 08:51
@kuflash the pull request you filed over at  jonathantneal/postcss-font-magician#65 does indeed fix the issue with both cssnano and cssnanonext [see repo with patch manually applied](https://github.com/WDD-Marv/cssnano-420/tree/with-kuflash-pr-65) :D

**Comment by kuflash** [comment] 2018-06-04 08:59
@WDD-Marv Yes, I also checked my fix on your repository. It helped a lot. Waiting for when they will accept PR)

**Comment by WDD-Marv** [comment] 2018-06-04 09:54
@kuflash do you happen to know where in the postcss docs is the part that describes the input/output formats that plugins are intended to support ?

**Comment by kuflash** [comment] 2018-06-04 09:59
@WDD-Marv now I'm trying to find this information. I need to somehow get the AST output to check the validity of the `decl.value`.

**Comment by WDD-Marv** [comment] 2018-06-04 10:10
@kuflash i'm thinking less about AST (code) and more about what it's meant to do (spec), i.e. is [the plugin linked to in the postcss docs](https://github.com/TrySound/postcss-value-parser) behaving correctly when it doesn't expect an array as input ?

**Comment by kuflash** [comment] 2018-06-04 10:14
@WDD-Marv good point. I'm will try use it's.

**Comment by kuflash** [comment] 2018-06-05 07:29
@WDD-Marv my [PR](https://github.com/jonathantneal/postcss-font-magician/pull/65) was accepted. I think you need to wait for the new release `postcss-font-magician` and you can close this issue.

**Comment by WDD-Marv** [comment] 2018-06-05 08:10
seems to work tentatively, although as you say, it's best to wait for new release :)

**Comment by evilebottnawi** [comment] 2018-06-05 11:31
@WDD-Marv @kuflash can you provide `css` what reproduce error?

**Comment by WDD-Marv** [comment] 2018-06-05 11:33
@evilebottnawi please refer to [this repo](https://github.com/WDD-Marv/cssnano-420)

**Comment by kuflash** [comment] 2018-06-05 12:02
@evilebottnawi the problem was not in the css, but in the fact that in `decl.value` passed the array, although the [documentation](http://api.postcss.org/declaration.es6.html#line33) there is expected to string.

Apparently, when the postcss is already doing the last stage of processing, then it normalized it, but when transmitting the result to another plug-in an error occurred.

**Comment by evilebottnawi** [comment] 2018-06-05 12:05
@kuflash hm, do you known who do it (plugin from `cssnano`)?

**Comment by WDD-Marv** [comment] 2018-06-05 12:08
@evilebottnawi it's the `postcss-value-parser` plugin receiving an array sent from `postcss-font-magician` when font magician is configured to use `font-display` in the `@font-face` declaration.

**Comment by evilebottnawi** [comment] 2018-06-05 12:10
@WDD-Marv in theory we should not modify standard postcss properties/fields for nodes to save compatibility with other plugins

**Comment by WDD-Marv** [comment] 2018-06-05 12:18
@evilebottnawi this is why i was wondering if `postcss-value-parser` was behaving according to spec in not accepting array values.

**Comment by WDD-Marv** [comment] 2018-06-05 14:06
p.s.; back to the original bug report, the bug was only occurring when certain components of cssnano were in use.

**Comment by evilebottnawi** [comment] 2018-06-05 14:07
Somebody can send PR with tests to ensure bug will be fixed or exists

**Comment by WDD-Marv** [comment] 2018-06-05 14:08
@evilebottnawi to `postcss-value-parser` ?

**Comment by evilebottnawi** [comment] 2018-06-05 14:09
@WDD-Marv to `cssnano`, here https://github.com/ben-eb/cssnano/tree/master/packages/cssnano/src/__tests__

**Comment by kuflash** [comment] 2018-06-05 14:13
I can create PR with test by this [example](https://github.com/ben-eb/cssnano/blob/master/packages/cssnano/src/__tests__/issue315.js).

**Comment by evilebottnawi** [comment] 2018-06-05 14:14
@kuflash looks like no issues :confused:

**Comment by kuflash** [comment] 2018-06-05 14:16
We not pass param `display` in fontMagician. If you pass it, you get an error. For [example](https://github.com/WDD-Marv/cssnano-420/blob/with-kuflash-pr-65/gulpfile.js#L7)

**Comment by evilebottnawi** [comment] 2018-06-05 14:19
@kuflash can you change test your test to failing?

**Comment by kuflash** [comment] 2018-06-05 14:21
@evilebottnawi sure. Now I will prepare an PR with this test.

**Closed** 2018-06-06 10:01 UTC
Labels: bug

**Comment by WDD-Marv** [comment] 2018-06-06 11:15
:D

**Comment by evilebottnawi** [comment] 2018-06-06 11:29
Any helping with other bugs welcome :+1:
