### ISSUE TITLE
Media queries optimisation

### ISSUE THREAD

**Issue by implico** [ben-eb/cssnano#210] opened 2016-06-15 00:16 UTC
It could be considered to add a grouping media queries plugin to optimisations:
https://github.com/Se7enSky/group-css-media-queries

But this one is not postcss-based as I can see.

**Comment by ben-eb** [comment] 2016-06-15 00:21
Duplicate of https://github.com/ben-eb/cssnano/issues/111.

**Closed by ben-eb** 2016-06-15 00:21 UTC
Labels: duplicate
