### ISSUE TITLE
Remove overridden rules

### ISSUE THREAD

**Issue by andrey-hohlov** [ben-eb/cssnano#200] opened 2016-05-28 11:31 UTC
Hi! 
Is there way to remove overridden rules like [csso](https://github.com/css/csso)?

For examle
```css
.btn {
  border: none;
  border: 1px solid red;
}
```
turn in:
```css
.btn {
  border: 1px solid red;
}
```

**Comment by ben-eb** [comment] 2016-05-28 12:53
Duplicate of https://github.com/ben-eb/cssnano/issues/86. 😄

**Closed by ben-eb** 2016-05-28 12:53 UTC
