### ISSUE TITLE
Multiple files handler for the "reduce-indents" 

### ISSUE THREAD

**Issue by loick** [ben-eb/cssnano#147] opened 2016-02-25 14:03 UTC
Hi, 

I am using cssnano with webpack and reactJS and I faced to an issue : 
I had 2 different stylesheets linked to the top of 2 components. The first one requires the second so webpack merged the CSS. 

I have keyframes in both of my stylesheets but when the output is created, cssnano uglifies the keyframe names. So on the first file I get a keyframe a, and on the second file a keyframe a also (which overrides the first one. 

Did you have this kind of problem ? 

Here is my conf : 

```javascript
import autoprefixer from 'autoprefixer';
import cssnano from 'cssnano';
import vars from 'postcss-simple-vars';
import calc from 'postcss-calc';
import nest from 'postcss-nested';
import ExtractTextPlugin from 'extract-text-webpack-plugin';

import variables from './variables';

const conf = {
    entry: {
        stage: [
            'webpack/hot/only-dev-server',
            'webpack-dev-server/client?http://localhost:8080',
            './js/stage.js'
        ]
    },
    output: {
        publicPath: 'http://localhost:8080/',
        filename: 'public/[name].js'
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                loaders: ['react-hot', 'jsx', 'babel?stage=0'],
                exclude: /node_modules/
            },
            {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract('style', 'css!postcss')
            },
            { test: /\.png$/, loader: "url-loader?limit=100000" },
            { test: /\.jpg$/, loader: "file-loader" }
        ]
    },
    plugins: [ new ExtractTextPlugin('css/app.css', {
            allChunks: true
    }) ],
    postcss() {
        return [
            vars({ variables : variables }),
            calc,
            nest,
            autoprefixer({ browsers: ['last 2 versions'] }),
            cssnano
        ];
    }
};

export default conf;
```

**Comment by loick** [comment] 2016-02-25 14:11
I probably should have posted on this plugin actually : https://github.com/ben-eb/postcss-reduce-idents

**Comment by ben-eb** [comment] 2016-02-25 15:10
Duplicate of https://github.com/ben-eb/postcss-reduce-idents/issues/5.

**Closed by ben-eb** 2016-02-25 15:10 UTC
