### ISSUE TITLE
DiscardComments does not work 

### ISSUE THREAD

**Issue by pvijeh** [ben-eb/cssnano#90] opened 2015-12-02 19:30 UTC
the DiscardComments does not remove comments.

**Comment by ben-eb** [comment] 2015-12-02 19:35
Can you please be a bit more specific? What is your input CSS and output CSS? How are you using cssnano? Is it an older version?

**Comment by pvijeh** [comment] 2015-12-02 19:44
Hi, 

I am using cssnano with postcss as part of my webpack setup.   

  postcss: function plugins(bundler) {
    return [
      require('postcss-import')({ addDependencyTo: bundler }),
      require('precss')(),
      require('autoprefixer')({ browsers: AUTOPREFIXER_BROWSERS }), 
      require('css-mqpacker')(),
      require('cssnano')({discardComments: {removeAll: true}})
    ];
  },
};

"postcss": "^5.0.10",
"postcss-import": "^7.1.3",
"precss": "^1.3.0",
"autoprefixer": "^6.1.0",
"css-mqpacker": "^4.0.0",


cssnano version: 3.3.2


I have switched to csswring for the time being

**Comment by ben-eb** [comment] 2015-12-02 20:24
Would you be able to put together a sample gist with this? I'm not a webpack user, I'm afraid.

**Comment by pvijeh** [comment] 2015-12-02 20:37
Yes,

Do you just want to see the webpack config file?

Here it is:

https://gist.github.com/pvijeh/f8843741037ad829527b

**Comment by dannybrown73** [comment] 2015-12-10 04:17
For me, it's the plugin order. If list precss before cssnano in my Gulp task comments are not removed. 

If I put precss after cssnano comments get removed, as expected.

<code>
var processors = [
        autoprefixer(),
        nano,
        precss // needs to come after nano 4 DiscardComments to remove comments?
    ];
</code>

"cssnano": "^3.3.2",
 "precss": "^1.3.0"

**Comment by benbrownlol** [comment] 2015-12-12 20:37
I had this issue also, moving cssnext under cssnano worked for me, wonder why this is.

// Dependencies
var gulp = require('gulp'),
	sass = require('gulp-sass'),
	postcss = require('gulp-postcss');

// PostCSS Processors
var processors = [
	require('autoprefixer')({ browsers: ['last 2 versions', '> 5%', 'ie 6-8']  }), // Apply vendor prefixes
	require('cssnano')({ discardComments: { removeAll: true }}), // Minify CSS
	require('cssnext')() // Usable CSS4
];

gulp.task('styles', function() {
	return gulp.src('dev/styles/styles.scss')
		.pipe(sass())
		.pipe(postcss(processors))
		.pipe(gulp.dest('prod/styles'));
});

**Comment by dfrankland** [comment] 2016-01-06 01:41
I found a work around for webpack! All that is is needed is to run multiple `postcss-loader` packs.

```js
module: {
  loaders: [
    {
      test: /\.scss$/,
      loaders: [
        'isomorphic-style-loader',
        'css-loader?' + (DEBUG ? 'sourceMap&' : '') +
        'modules&localIdentName=[name]_[local]_[hash:base64:3]',
        'postcss-loader?pack=minimize',
        'postcss-loader?pack=compile',
        'postcss-loader?pack=load', // works backwards so import should be last
      ],
    },
  ],
},

postcss: (bundler) => {
  return {
    load: [require('postcss-import')({ addDependencyTo: bundler })],
    compile: [
      require('precss')(),
      require('autoprefixer')({ browsers: AUTOPREFIXER_BROWSERS }),
    ],
    minimize: DEBUG ? [] : [
      require('cssnano')({
        autoprefixer: false,
        discardComments: { removeAll: true },
      }),
    ],
  };
},
```

**Comment by PhilRedm** [comment] 2016-03-01 19:54
Moving cssnext under cssnano also worked for me.

**Comment by jmurzy** [comment] 2016-03-03 22:17
I can also confirm that the issue seems to be running cssnano after cssnext. 🤒

**Comment by ben-eb** [comment] 2016-03-03 22:25
This is caused by https://github.com/postcss/postcss-filter-plugins - will be removed for v4. To resolve, pass `{filterPlugins: false}`.

**Comment by jmurzy** [comment] 2016-03-03 22:33
@ben-eb That did the trick — thanks! 👍

**Comment by ben-eb** [comment] 2017-06-01 10:21
Resolved in https://github.com/ben-eb/cssnano/releases/tag/v4.0.0-rc.0.

**Closed by ben-eb** 2017-06-01 10:21 UTC
Labels: bug
