### ISSUE TITLE
Warning: undefined [postcss-discard-empty]

### ISSUE THREAD

**Issue by mikestopcontinues** [ben-eb/cssnano#213] opened 2016-06-20 18:10 UTC
With a recent update, cssnano has been outputting the following on every build for every file that has an empty rule. I can just disable postcss-reporter, but I don't think its a necessary message given that cssnano's reason for being is to compress css.

```
node_modules/sanitize.css/sanitize.css
undefined [postcss-discard-empty]
```

**Comment by ben-eb** [comment] 2016-06-20 19:38
Duplicate of #212.

https://github.com/ben-eb/cssnano/issues/212#issuecomment-227114052

**Closed by ben-eb** 2016-06-20 19:38 UTC
Labels: duplicate
