### ISSUE TITLE
TypeError: Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by ryanelian** [ben-eb/cssnano#400] opened 2017-08-14 21:13 UTC
cssnano 4.0.0-rc.2
NodeJS 6.11.2
Yarn 0.27.5

Issue isolated to the css file and cssnano: [brokencss.zip](https://github.com/ben-eb/cssnano/files/1223460/brokencss.zip)

Run `npm run boom` using above zip.

```
PS C:\Users\Ryan\Downloads\brokencss> npm run boom

> brokencss@1.0.0 boom C:\Users\Ryan\Downloads\brokencss
> postcss boom.css --use cssnano

× Processing boom.css
TypeError: Cannot read property 'trim' of undefined
    at Object.attribute (C:\Users\Ryan\Downloads\brokencss\node_modules\postcss-minify-selectors\dist\index.js:44:46)
    at C:\Users\Ryan\Downloads\brokencss\node_modules\postcss-minify-selectors\dist\index.js:150:31
    at C:\Users\Ryan\Downloads\brokencss\node_modules\postcss-selector-parser\dist\selectors\container.js:176:26
    at Selector.each (C:\Users\Ryan\Downloads\brokencss\node_modules\postcss-selector-parser\dist\selectors\container.js:159:22)
    at Selector.walk (C:\Users\Ryan\Downloads\brokencss\node_modules\postcss-selector-parser\dist\selectors\container.js:175:21)
    at C:\Users\Ryan\Downloads\brokencss\node_modules\postcss-selector-parser\dist\selectors\container.js:179:31
    at Root.each (C:\Users\Ryan\Downloads\brokencss\node_modules\postcss-selector-parser\dist\selectors\container.js:159:22)
    at Root.walk (C:\Users\Ryan\Downloads\brokencss\node_modules\postcss-selector-parser\dist\selectors\container.js:175:21)
    at Processor.func (C:\Users\Ryan\Downloads\brokencss\node_modules\postcss-minify-selectors\dist\index.js:144:19)
    at Processor.processSync (C:\Users\Ryan\Downloads\brokencss\node_modules\postcss-selector-parser\dist\processor.js:53:14)
    at getParsed (C:\Users\Ryan\Downloads\brokencss\node_modules\postcss-minify-selectors\dist\index.js:34:59)
    at optimise (C:\Users\Ryan\Downloads\brokencss\node_modules\postcss-minify-selectors\dist\index.js:141:21)
```

Original SCSS source code: https://github.com/ryanelian/instapack/tree/master/templates/angular-material/client/css

> btw, cssnano 3.10.0 processed the file successfully.

**Comment by andyjansson** [comment] 2017-08-14 21:40
Can you put the contents of `boom.css` on codepen?

**Comment by ryanelian** [comment] 2017-08-14 21:44
https://codepen.io/anon/pen/prWxvw

**Comment by andyjansson** [comment] 2017-08-15 06:32
Okay, I've found the offending selector: 

```
[ng\:cloak]
```

I'll investigate further into what the cause might be.

**Comment by andyjansson** [comment] 2018-04-19 17:33
The fix has landed in the upstream package. Introducing the new version will henceforth be tracked from #451

**Closed by andyjansson** 2018-04-19 17:33 UTC
