### ISSUE TITLE
in case of insensitivity

### ISSUE THREAD

**Issue by tomhodgins** [ben-eb/cssnano#321] opened 2016-12-16 06:13 UTC
```css
.test {
  background: red;
}
.TEST {
  color: blue;
}
```

## correct minification

```css
.test{background:red;color:blue}
```

- class names (and many other things) are not case sensitive in CSS

## CSSnano output

```css
.test{background:red}.TEST{color:blue}
```

- `.test`, `.TEST` and any combination of lowercase and uppercase letters in class selectors are equivalent

**Comment by ben-eb** [comment] 2016-12-16 12:28
Duplicate of https://github.com/ben-eb/cssnano/issues/197.

**Closed by ben-eb** 2016-12-16 12:28 UTC
